# Generated by Django 4.1.3 on 2022-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='time',
        ),
        migrations.AddField(
            model_name='petition',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
