# Generated by Django 4.1.3 on 2022-11-27 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_petition_time_petition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('cur', 'Сбор подписей'), ('viw', 'На рассмотрении'), ('res', 'Готов ответ')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=14, null=True)),
                ('number', models.CharField(max_length=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
